### ISSUE TITLE
Porównanie z przeciwnikiem

### ISSUE THREAD

**Issue by fryzjer69** [eldakar/arkatt#12]
Czy możemy dodać aby przy spojrzeniu na daną osobę (obejrzenie kogoś ) na dole dodawało porównanie statów ? 

Porównaj siłę z 
Porównaj zręczność z 
Porównaj wytrzymałość z 

I żeby w skróconej formie dorzucało to na dole do jego opisu z kolorkiem:

Czerwonym jeśli jesteś mniej silny/zręczny/wytrzymaly
Żółtym jesli jesteś tak samo
Zielonym jeśli jesteś mocniejszy

Thx

**Comment by drzewka** [comment]
Ja bym to dała pod binda. Niektóre zawody nie mają nawet oceny przeciwnika, np. partyzant. To moze byc irytujace na dluzsza mete dla takiego kogos.

**Comment by eldakar** [comment]
to tez zrobione ale w branchu arkatt-nomap :)
