### ISSUE TITLE
Alternatywne ataki

### ISSUE THREAD

**Issue by fryzjer69** [eldakar/arkatt#14]
Zapytanie o komendę /cel ktora wyznaczalaby cel, na przyklad ustawiam sobie /cel orka lub /cel moriego i pod jakims klawiszem (f9?) od razu atakuje. Byłoby to o tyle wygodne, że w przypadku pvm możnaby mieć atak przygotowany przed wejściem na lokacje.

**Comment by eldakar** [comment]
ok w main.tin wrzuc #var KEY_F8 {twoj skrot} 

cel orka
cel kogos

odmieniasz, zebym ja nie musial :)
