### ISSUE TITLE
Aktualny BIND

### ISSUE THREAD

**Issue by fryzjer69** [eldakar/arkatt#18]
Przydalaby sie informacja obok prompta o tym jaki jest aktualny BIND

F4 - wez monety

W walce to ginie.

**Comment by eldakar** [comment]
![quickbindy](https://cloud.githubusercontent.com/assets/11772152/9106974/dee9a2c4-3c1b-11e5-9660-d65e8beb498e.png)

cos takiego bedzie
dlatego ze Twoja mapka mi troszke sie gryzie z bindami, zrobie oddzielne quickaliasy do chodzenia w przejscia niestandardowe...

**Comment by eldakar** [comment]
![capture](https://cloud.githubusercontent.com/assets/11772152/9115786/c8893d54-3c58-11e5-9195-2fa18dfcabbe.PNG)
no i zrobione ;)

**Comment by fryzjer69** [comment]
Spoko :-) 

PZDR,
KW

Dnia 6 sie 2015 o godz. 17:33 eldakar <notifications@github.com> napisał(a):
