### ISSUE TITLE
na macu nie dzialaja < i > 

### ISSUE THREAD

**Issue by DorienCragen** [eldakar/arkatt#19]

**Comment by eldakar** [comment]
kiedy sciagales update? :)

**Comment by eldakar** [comment]
`#line substitute {variables} {#macro {>} {tryb_prompta_fw}};
#line substitute {variables} {#macro {<} {tryb_prompta_bk}};`

tu sa definicje makr z pliku macros.tin

sprobuj recznie uruchomic oba aliasy tryb_prompta_fw, tryb_prompta_bk i daj znac  czy dziala

**Comment by DorienCragen** [comment]
probowalem nie dziala, pulla zrobilem niedawno zmianialem tez #var _prompt_tryb {chat} i tez nie poskutkowalo, ja uzywam do podobnych rzeczy switch casea, rzuce okiem wieczorem na to

**Comment by eldakar** [comment]
dla przyszlych pokolen: wymagany update clienta do wersji 2.0.1.1
