### ISSUE TITLE
na macu nie dziala #mapper

### ISSUE THREAD

**Issue by DorienCragen** [eldakar/arkatt#20]

**Comment by eldakar** [comment]
#mapper to druga sejsa ktora dziala w tle pierwszej "rpg"

gdy uruchamiasz tintina, on tworzy pierw sesje mappera (laczy sei do niego), a jesli nie moze sie polaczyc to odrazu przechodzi do sesji "rpg"

musisz tf-mapper uruchomic pierwszy, dopiero potem tintina.

**Comment by DorienCragen** [comment]
wiem u mnei dziala tak samo, z pewnych wzgledow wrocilem do mapy tintinowej, brzydziej wyglada ale ma wiecej mozliwosci, w tf maperze trzeba uzyc chyba 127.0.0.1 zamiast localhost nie jestem pewien
