### ISSUE TITLE
Lazik

### ISSUE THREAD

**Issue by fryzjer69** [eldakar/arkatt#21]
Przydałby się przycisk za pomocą którego postać idzie w kierunku przeciwnym do którego przyszła. Oczywiście pod warunkiem, że są dwa wyjścia. To ułatwia ucieczkę na trakcie.

Standardowo w swoim poprzednim kliencie używałem do tego przycisku 5 na numpadzie ale może być to inny przycisk, byle był blisko "łazika".

**Comment by eldakar** [comment]
zrobione pod aliasem #alias {idz_prosto} , ktory trzeba sobie podmakrowac.  - zrobie schemat tego makra w main.tin 

ta wersja dziala tylko z tf-mapperem, czyli jesli nawet mud nie odda wyjsc dostepnych, a mamy wyjscia na tfmapperze - > komenda ruszy do przodu. wyjscia te musza byc zmapowane jako standardowe, nie w trybie "custom exit"

oddzielnie napisalbym wersje bez-mapowa, zeby pobierala tylko kierunki z muda. bedzie to czescia migracji clienta na bezmapowy tryb ;)

**Comment by eldakar** [comment]
tak samo jak oryginalny lazik, wersja na windows nie dziala :+1:
