### ISSUE TITLE
aliasy stowarzyszenia kompanii gryfa zamiast ogolnych np nazabij i inne

### ISSUE THREAD

**Issue by ssnakey** [eldakar/arkatt#21]

**Comment by eldakar** [comment]
ok zrobilem update
w pliku m.tin dodaj alias
#alias zabijcmd TWOJA_KOMENDA_ZABIJANIA;

domyslnie jest 
#alias zabijcmd zabij

**Comment by eldakar** [comment]
ok otwieram issue jeszcze raz - spisz klawisze
