### ISSUE TITLE
kody klawiszy powyciagane do m.tin

### ISSUE THREAD

**Issue by ssnakey** [eldakar/arkatt#22]

**Comment by eldakar** [comment]
plik m.tin trzymaj w oddzielnym katalogu

napisz o ktory klawisz CI chodzi

**Comment by ssnakey** [comment]
o wiekszosc najgorsze ze to u kazdego bedzie inaczej a to dosc istotne moze z racji tego bysmy trzymali wszystkie macra klawisze funkcyjne i calego numeryka w pliku m.tin ? bo czesc ustawien jest pewnie w innych plikach.... cholera wie jakich

**Comment by eldakar** [comment]
done
