### ISSUE TITLE
bledne zliczanie wchodzacych wychodzacych z lokacji

### ISSUE THREAD

**Issue by ssnakey** [eldakar/arkatt#23]
[+3] Postawny charyzmatyczny kapitan, dwaj ciemnoocy postawni straznicy i umiesniony wysoki straznik przybywaja z polnocnego-zachodu.
[-3] Postawny charyzmatyczny kapitan, dwaj ciemnoocy postawni straznicy i umiesniony wysoki straznik podazaja na polnocny-zachod.

**Comment by eldakar** [comment]
usuniete z kodu
