### ISSUE TITLE
Uszkodzone mapy klienta www

### ISSUE THREAD

**Issue by Ralandil** [eldakar/arkatt#31]
Znaki backslasha "\" w wielu miejscach zastąpiono cyfrą "9".

**Comment by eldakar** [comment]
czolem
zrobilem to specjalnie, zeby moc zastepowac slasz (czasami sypie sie bo uzywany jest tez do lamania znakow specjalnych)

spojrzyj na plik fetchmaps.sh w katalogu tools, mozesz go sobie naprawic samemu
