### ISSUE TITLE
Kolorek na magiczne itemy

### ISSUE THREAD

**Issue by rozmiarD** [eldakar/arkatt#41]
np kolorek 94

`<?xml version="1.0" encoding="ISO-8859-1" ?>
<cmud>
  <var name="magiki" type="StringList" sorted="1">
    <value>adamantytowa szpiczasta partyzane|antyczny zdobiony sztylet|azurowy koscistobialy amulet|blekitno-srebrna herbowa tarcze|ciemna owalna maska|ciemna owalna maske|ciemnogranatowy smukly helm|ciezki krwisty amulet|czarnoblekitne pulsujace morgensterny|czarnoblekitny pulsujacy morgenstern|czarny prosty diadem|czarny zdobiony amulet|czerwony zakrwawiony pierscien|dluga czarna szate|dluga krasnoludzka bajdane|dlugi runiczny korbacz|dlugie czarne szaty|dlugie krasnoludzkie bajdany|dwureczne adamantytowe mloty bojowe|dwureczny adamantytowy mlot bojowy|gigantyczny granitowy mlot|gwiezdny topor|iskrzaca zdobiona bulawe|jasniejace zdobione jatagany|jasniejacy zdobiony jatagan|kosciany kilof|kruczoczarny dlugi plaszcz|kruczoczarny misterny miecz|krysztalowy dwureczny korbacz|kunsztowny lekki pancerz|kunsztowny mithrylowy topor bojowy|lekka lsniaca bransoleta|lodowy lsniacy sztylet|lsniaca plomienista tarcza|lsniaca plomienista tarcze|lsniacy krysztalowy wisior|masywny amulet z czarnym opalem|masywny oksydowany pas|masywny wyszczerbiony tasak|misterny obosieczny topor|mithrylowa mahakamska kolczuge|niebieskawa zdobiona bulawa|niebieskawa zdobiona bulawe|niebieskawe zdobione bulawy|niebieskie zdobione bulawy|niepozorny barwny pierscien|niewielka dziesiecioramienna gwiazda z mosiadzu|niewielka dziesiecioramienna gwiazde z mosiadzu|niewielki krwawnikowy pierscien|niewielki zmatowialy pierscien|ogromny ognisty trojzab|opalizujacy runiczny topor obosieczny|ornamentowany kruczoczarny helm wielki|ozdobny skorzany plecak|polprzezroczysta migotliwa maczuga|polprzezroczysta migotliwa maczuge|polprzezroczysty migotliwy drag|polprzezroczysty migotliwy miecz|polprzezroczysty migotliwy mlot|polprzezroczysty migotliwy sztylet|polprzezroczysty migotliwy topor|polyskliwy smukly espadon|poszczerbione obureczne miecze|poszczerbiony obureczny miecz|pozlacane okulary z niebieskawych szkielek|smukly demoniczny miecz|smukly zmiennoksztaltny miecz|smuklym demonicznym mieczem|smuklym zmiennoksztaltnym mieczem|snieznobiala luskowa kolczuge|snieznobialy lsniacy pancerz|srebrzysta kosa bojowa|srebrzysta kose bojowa|starozytna runiczna zbroja plytowa|starozytna runiczna zbroje plytowa|starozytnego pancerza|stary matowy pancerz|strzelisty zasniedzialy helm|strzelisty zlocisty helm|szkarlatny dlugi talwar|szmaragdowozielony misterny plaszcz|waski kunsztowny sihill|wielki runiczny mlot wojenny|zdobione jasniejace mloty bojowe|zdobiony dlugi lewak|zdobiony jasniejacy mlot bojowy|zdobiony zloty pierscien|zielony luskowaty plaszcz</value>
    <json>["adamantytowa szpiczasta partyzane","antyczny zdobiony sztylet","azurowy koscistobialy amulet","blekitno-srebrna herbowa tarcze","ciemna owalna maska","ciemna owalna maske","ciemnogranatowy smukly helm","ciezki krwisty amulet","czarnoblekitne pulsujace morgensterny","czarnoblekitny pulsujacy morgenstern","czarny prosty diadem","czarny zdobiony amulet","czerwony zakrwawiony pierscien","dluga czarna szate","dluga krasnoludzka bajdane","dlugi runiczny korbacz","dlugie czarne szaty","dlugie krasnoludzkie bajdany","dwureczne adamantytowe mloty bojowe","dwureczny adamantytowy mlot bojowy","gigantyczny granitowy mlot","gwiezdny topor","iskrzaca zdobiona bulawe","jasniejace zdobione jatagany","jasniejacy zdobiony jatagan","kosciany kilof","kruczoczarny dlugi plaszcz","kruczoczarny misterny miecz","krysztalowy dwureczny korbacz","kunsztowny lekki pancerz","kunsztowny mithrylowy topor bojowy","lekka lsniaca bransoleta","lodowy lsniacy sztylet","lsniaca plomienista tarcza","lsniaca plomienista tarcze","lsniacy krysztalowy wisior","masywny amulet z czarnym opalem","masywny oksydowany pas","masywny wyszczerbiony tasak","misterny obosieczny topor","mithrylowa mahakamska kolczuge","niebieskawa zdobiona bulawa","niebieskawa zdobiona bulawe","niebieskawe zdobione bulawy","niebieskie zdobione bulawy","niepozorny barwny pierscien","niewielka dziesiecioramienna gwiazda z mosiadzu","niewielka dziesiecioramienna gwiazde z mosiadzu","niewielki krwawnikowy pierscien","niewielki zmatowialy pierscien","ogromny ognisty trojzab","opalizujacy runiczny topor obosieczny","ornamentowany kruczoczarny helm wielki","ozdobny skorzany plecak","polprzezroczysta migotliwa maczuga","polprzezroczysta migotliwa maczuge","polprzezroczysty migotliwy drag","polprzezroczysty migotliwy miecz","polprzezroczysty migotliwy mlot","polprzezroczysty migotliwy sztylet","polprzezroczysty migotliwy topor","polyskliwy smukly espadon","poszczerbione obureczne miecze","poszczerbiony obureczny miecz","pozlacane okulary z niebieskawych szkielek","smukly demoniczny miecz","smukly zmiennoksztaltny miecz","smuklym demonicznym mieczem","smuklym zmiennoksztaltnym mieczem","snieznobiala luskowa kolczuge","snieznobialy lsniacy pancerz","srebrzysta kosa bojowa","srebrzysta kose bojowa","starozytna runiczna zbroja plytowa","starozytna runiczna zbroje plytowa","starozytnego pancerza","stary matowy pancerz","strzelisty zasniedzialy helm","strzelisty zlocisty helm","szkarlatny dlugi talwar","szmaragdowozielony misterny plaszcz","waski kunsztowny sihill","wielki runiczny mlot wojenny","zdobione jasniejace mloty bojowe","zdobiony dlugi lewak","zdobiony jasniejacy mlot bojowy","zdobiony zloty pierscien","zielony luskowaty plaszcz"]</json>
  </var>
</cmud>
`

**Comment by eldakar** [comment]
zrobione
plik kolorki.tin
