### ISSUE TITLE
Info o poczcie w prompt

### ISSUE THREAD

**Issue by baranno** [eldakar/arkatt#50]
Przydaloby sie info ze jest nowa poczta i resetowalo po wyslaniu ptaka/odwiedzeniu poczty.

Czeka na ciebie nieprzeczytana poczta

(^Masz nowa poczte od [A-Za-z]+\.$)

^((Nie otrzymal.s|Nie masz) zadnych|Kasuje listy|List : )

Wysylasz .* na poczte.

**Comment by eldakar** [comment]
done, uzywajac gmcp:

#event {IAC SB GMCP mail.state IAC SE} {
	#var MAILMSG {%0};
	#if {"$MAILMSG[unread]" == "true"} {
		#var prompt_unread {${c_stan_niski}POCZ<088>};
		hpbar;
	} {
		#var prompt_unread {<088>----};
		hpbar;
	}
}
