### ISSUE TITLE
Wzornik kolorow?

### ISSUE THREAD

**Issue by drzewka** [eldakar/arkatt#8]
Moja propozycja wzornika zlozonego z 20 kolorow, na ktorych mialyby sie opierac wszystkie skrypty. Dzieki temu zachowamy spojnosc kolorystyczna. Trzeba porownac wyswietlanie u mnie i u Ciebie. Co o tym sadzisz?

Dodalam plik wzornik.tin do arkatt-master. Wyglada to tak:

![wzornik](https://cloud.githubusercontent.com/assets/12633641/7898207/eeba548a-06f8-11e5-815c-5ebd948673df.png)

**Comment by eldakar** [comment]
Super. Dolacze tutaj moj screenshot. Ciemny niebieski jak dla mnie troszke za bardzo sie zlewa

Jak sie zgodzimy na kolory to porobimy dla nich zmienne :)

**Comment by eldakar** [comment]
![kolory](https://cloud.githubusercontent.com/assets/11772152/7919642/95dbfa40-0891-11e5-85fc-101be579ab87.png)

**Comment by eldakar** [comment]
mysle ze mozemy sie zgodzic na ten zestaw.

088 to reset wszystkiego, jesli Twoj terminal ma domyslny kolor pisania zolty, to 088 resetuje do zoltego

**Comment by drzewka** [comment]
Pod <088> tez mam jasny szary. Zatem zestaw zatwierdzony. Ciemny niebieski, ktory Cie tak uwieral przyda sie do mapy. 
Dodatkowo w kolorach muda ustawilam sobie kolor mowy / krzyku / szeptu / emocji do mnie na zolty.

**Comment by eldakar** [comment]
super :+1:
